<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS_Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Midterm Exam


In [1]:
import numpy as np

In [12]:
#Question 1. Create a Python code that displays a square matrix whose length is 5
A = np.array([[2,4,6,8,10],[12,14,16,18,20],[22,24,26,28,30],[32,34,36,38,40],[42,44,46,48,50,]])
print(A)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [13]:
#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero
B= np.array([[3,6,9],[0,12,15],[0,0,18]])
print(C)

[[ 3  6  9]
 [ 0 12 15]
 [ 0  0 18]]


In [11]:
#Question 3. Create a Python code that displays a square matrix which is symmetrical 
K = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(K)
print("\n")
print(np.transpose(K))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
#Question 4. What is the inverse of matrix C? Show your solution by python coding. 
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) 
print(C)

inv_C = np.linalg.inv(C)
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [16]:
#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) 
print(C)

print(np.linalg.det(C))
print(round(np.linalg.det(C)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


In [23]:
#Question 6. Find the roots of the linear equations by showing its python codes
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(A)
print("\n")
inv_A = np.linalg.inv(A)
print(inv_A)
print("\n")
B = np.array([[3.4],[8.8],[19.2]])
print(B)
print("\n")
C = np.dot(inv_A,B)
print(C)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]


[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]


[[ 3.4]
 [ 8.8]
 [19.2]]


[[0.2]
 [0.4]
 [0.8]]
