<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS_FINAL_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FINAL EXAM**

In [1]:
import numpy as np

In [4]:
#Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


In [6]:
#Problem 2. Solve each system: (30 points)
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

Apinv = np.linalg.pinv(A)

x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


In [3]:
#Problem 3. Consider the matrix, (40 points)
#Find the eigenvalue/s
#Find the eigenvectors

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)
#let b be eigenvalue/s; let c be eigenvectors
b,c = np.linalg.eig(A)
print("The eigenvalue/s is/are", b)
print("The eigenvectors is/are", c)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are [-1.  3.  2.]
The eigenvectors is/are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
