<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS__Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PRELIM EXAM**


In [2]:
import numpy as np

## GOOD AFTERNOON MA'AM, I MADE TWO EXAMPLES FOR QUESTION #1 AND QUESTION #2.

In [10]:
#QUESTION 1
C = np.array ([[1,2,3,4], [5,1,6,7], [8,9,1,0], [2,3,4,1]])
print(C)

[[1 2 3 4]
 [5 1 6 7]
 [8 9 1 0]
 [2 3 4 1]]


In [14]:
#QUESTION 1.1 (for question 2.1)
C = np.array ([1,1,1,1])
print(np.diag(C))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
#QUESTION 2
C = np.array ([[1,2,3,4], [5,1,6,7], [8,9,1,0], [2,3,4,1]])
print(C*C)

[[ 1  4  9 16]
 [25  1 36 49]
 [64 81  1  0]
 [ 4  9 16  1]]


In [16]:
#QUESTION 2.1 (in relation with question 1.1)
C = np.array ([1,1,1,1])
C = (np.diag(C))
print(np.multiply(C,C))


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [17]:
#QUESTION 3

A = np.array([2,7,4])
B = np.array([3,9,8])
print(np.cross(A,B))

[20 -4 -3]
