<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/Bagalawis_Python_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Python program for Inverse and Transpose of Matrices**

In [21]:
import numpy as np

In [23]:
#3x3 array
A = np.array ([[1,7,7], [2,-6,8], [3,9,4]])
print(A)

[[ 1  7  7]
 [ 2 -6  8]
 [ 3  9  4]]


In [24]:
#Inverse Matrix
A = np.array ([[1,7,7], [2,-6,8], [3,9,4]])
A_inverse = (np.linalg.inv(A))
print(A_inverse)

[[-0.35820896  0.13059701  0.36567164]
 [ 0.05970149 -0.06343284  0.02238806]
 [ 0.13432836  0.04477612 -0.07462687]]


In [25]:
#Transpose matrix
A = np.array ([[1,7,7], [2,-6,8], [3,9,4]])
A_transpose = A.transpose()
print (A_transpose)

[[ 1  2  3]
 [ 7 -6  9]
 [ 7  8  4]]
