<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS_Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Practical Lab Exam 1**

In [1]:
import numpy as np

##PROBLEM 1


In [22]:
#A.)WY

W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
result = np.dot(W,Y)
print(result)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [23]:
#B.)Z+Z

Z = np.array([[0,1], [2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


In [25]:
#C.)3X

X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(X*3)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


##PROBLEM 2


In [20]:
#A.)The product (YW)^2 is not defined


W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
result = np.dot(Y,W)
print(result*result)

#the statement is false because it has a defined answer.

[[25 49]
 [16 16]]


In [21]:
#B.)WY-X

WY = np.array([[1,5,-6],[2,6,-4],[3,5,2]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(WY-X)

#the statement is true because the result is the same with the result shown on blackboard.

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [18]:
#C.)YW-Z^2

YW = np.array([[5,-7],[4,4]])
Z = np.array([[0,1], [2,3]])
print(YW-Z*Z)

#the statement is false because it shows a different answer with the result shown on blackboard.

[[ 5 -8]
 [ 0 -5]]
