<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS_LINEAR_TRANSFORMATION_DEMO2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[4,1,8],[10,26,26],[8,26,21]])
print (A)
inv_A=np.linalg.inv(A)
print(A)

B = np.array ([[44,],[128],[214]])
print(B)

#AA^1z = .A^-1
X = np.dot(inv_A,B)
print(X)

[[ 4  1  8]
 [10 26 26]
 [ 8 26 21]]
[[ 4  1  8]
 [10 26 26]
 [ 8 26 21]]
[[ 44]
 [128]
 [214]]
[[195.58490566]
 [ 25.13207547]
 [-95.43396226]]
