<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/Bagalawis_Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [7]:
import numpy as np

In [9]:
#Sum
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [10]:
#Difference1
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]


In [11]:
#Difference2
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(B-B)

[[0 0]
 [0 0]]
