<a href="https://colab.research.google.com/github/KCalvin23/Linear-Algebra-58020/blob/main/BAGALAWIS_Python_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print (A)
inv_A=np.linalg.inv(A)
print(A)

B = np.array ([[5,],[6],[8]])
print(B)

#XX^1z = .A^-1
X = np.dot(inv_A,B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[5]
 [6]
 [8]]
[[ 4.]
 [-1.]
 [ 2.]]
